config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root to: 'pictures#index'
 resources :pictures do
  resources :comments, omly: :create
  collection do
    get 'search'
  end
 end
 resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
  belongs_to :user  

  validates :text, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :text,    presence: true
  validates :image,   presence: true
  validates :account, presence: true

  belongs_to :user
  has_many :comments
  has_one_attached :image

  def self.search(search)
    if search != ""
      Picture.where('text LIKE(?)', "%#{search}%")
    else
      Picture.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pictures
  has_many :comments

  validates :nickname, presence: true
  validates :nickname, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/pictures/#{comment.picture.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, picture_id: params[:picture_id])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture, except: [:index, :new, :create, :search]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.includes(:user).order("created_at DESC")
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.valid?
      @picture.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    picture = Picture.find(params[:id])
    picture.update(picture_params)
  end
  
  def show
    @comment = Comment.new
    @comments = @picture.comments.includes(:user)
  end

  def search
    @pictures = Picture.search(params[:keyword])
  end

  private
  def picture_params
    params.require(:picture).permit(:image, :text, :account).merge(user_id: current_user.id)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def move_to_index
    redirect_to root_path unless current_user == @picture.user
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @pictures = user.pictures
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>M-Studio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">M-Studio</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
           <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
            <%= link_to "投稿する", new_picture_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
        <footer>
      <p>
        Copyright M-Studio 2021.
      </p>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
    <%= form_with model: picture, local: true do |form| %>
     <%= render 'layouts/error_messages', model: form.object %>
      <%= form.file_field :image %>
      <%= form.text_field :account, placeholder: "その他アカウントのURL"%>
      <%= form.text_area :text, placeholder: "ここに制作ソフトや制作期間を入力してください", rows: "10" %>
      <%= form.submit "SEND" %>
    <% end %>

app/views/pictures/_picture.html.erb
    <div class="content_post" >
    <%= image_tag picture.image.variant(type: :grayscale), class: 'p-image' %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', picture_path(picture.id), method: :get %>
          </li>
          <% if user_signed_in? && current_user.id == picture.user_id %>
          <li>
            <%= link_to '編集', edit_picture_path(picture.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', picture_path(picture.id), method: :delete %>
          </li>
          <% end %>
        </ul>
      </div>
      <p><%= picture.account %></p>
      <span class="name">
        <a href="/users/<%= picture.user.id %>">
          <span>投稿者</span><%= picture.user.nickname %>
        </a>
      </span>
       <span><h3><%= picture.text %></h3></span>
    </div>

app/views/pictures/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/pictures/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="contents row">
<div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { picture: @picture } %>
  </div>
</div>

app/views/pictures/index.html.erb
<%= form_with(url: search_pictures_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @pictures.each do |picture| %>
   <%= render partial: "picture", locals: { picture: picture } %>
  <% end %>
</div>

app/views/pictures/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= render partial: "form", locals: { picture: @picture } %>
  </div>
</div>

app/views/pictures/search.html.erb
<%= form_with(url: search_pictures_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @pictures.each do |picture| %>
    <%= render partial: "picture", locals: { picture: picture } %>
  <% end %>
</div>

app/views/pictures/show.html.erb
<div class="contents row">
  <div class="content_post" >
    <%= image_tag @picture.image.variant(type: :grayscale), class: 'p-image' %>
    <% if user_signed_in? && current_user.id == @picture.user_id %>
    <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_picture_path(@picture.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', picture_path(@picture.id), method: :delete %>
        </li>
      </ul>
    </div>
    <% end %>
    <p><%= @picture.text %></p>
    <span class="name">
      <a href="/users/<%= @picture.user.id %>">
        <span>投稿者</span><%= @picture.user.nickname %>
      </a>
    </span>
  </div>
    <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@picture, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
        <div class="comments">
      <%= form_with(model: @picture, local: true) do |f| %>
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @pictures.each do |picture| %>
   <%= render partial: "pictures/picture", locals: { picture: picture } %>
  <% end %>
</div>